// lib/theme/theme.dart
import 'package:flutter/material.dart';
import 'type.dart';
import 'color.dart';


final lightTheme = ThemeData(
  useMaterial3: true,
  colorScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: primaryLight,
    onPrimary: onPrimaryLight,
    primaryContainer: primaryContainerLight,
    onPrimaryContainer: onPrimaryContainerLight,
    secondary: secondaryLight,
    onSecondary: onSecondaryLight,
    secondaryContainer: secondaryContainerLight,
    onSecondaryContainer: onSecondaryContainerLight,
    tertiary: tertiaryLight,
    onTertiary: onTertiaryLight,
    tertiaryContainer: tertiaryContainerLight,
    onTertiaryContainer: onTertiaryContainerLight,
    error: errorLight,
    onError: onErrorLight,
    errorContainer: errorContainerLight,
    onErrorContainer: onErrorContainerLight,
    surface: surfaceLight,
    onSurface: onSurfaceLight,
    surfaceDim: surfaceDimLight,
    surfaceBright: surfaceBrightLight,
    surfaceContainerLowest: surfaceContainerLowestLight,
    surfaceContainerLow: surfaceContainerLowLight,
    surfaceContainer: surfaceContainerLight,
    surfaceContainerHigh: surfaceContainerHighLight,
    surfaceContainerHighest: surfaceContainerHighestLight,
    outline: outlineLight,
    outlineVariant: outlineVariantLight,
    shadow: scrimLight,
    scrim: scrimLight,
    inverseSurface: inverseSurfaceLight,
    onInverseSurface: inverseOnSurfaceLight,
    inversePrimary: inversePrimaryLight,
    surfaceTint: primaryLight,
  ),
  textTheme: textTheme,
);

final darkTheme = ThemeData(
  useMaterial3: true,
  colorScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: primaryDark,
    onPrimary: onPrimaryDark,
    primaryContainer: primaryContainerDark,
    onPrimaryContainer: onPrimaryContainerDark,
    secondary: secondaryDark,
    onSecondary: onSecondaryDark,
    secondaryContainer: secondaryContainerDark,
    onSecondaryContainer: onSecondaryContainerDark,
    tertiary: tertiaryDark,
    onTertiary: onTertiaryDark,
    tertiaryContainer: tertiaryContainerDark,
    onTertiaryContainer: onTertiaryContainerDark,
    error: errorDark,
    onError: onErrorDark,
    errorContainer: errorContainerDark,
    onErrorContainer: onErrorContainerDark,
    surface: surfaceDark,
    onSurface: onSurfaceDark,
    surfaceDim: surfaceDimDark,
    surfaceBright: surfaceBrightDark,
    surfaceContainerLowest: surfaceContainerLowestDark,
    surfaceContainerLow: surfaceContainerLowDark,
    surfaceContainer: surfaceContainerDark,
    surfaceContainerHigh: surfaceContainerHighDark,
    surfaceContainerHighest: surfaceContainerHighestDark,
    outline: outlineDark,
    outlineVariant: outlineVariantDark,
    shadow: scrimDark,
    scrim: scrimDark,
    inverseSurface: inverseSurfaceDark,
    onInverseSurface: inverseOnSurfaceDark,
    inversePrimary: inversePrimaryDark,
    surfaceTint: primaryDark,
  ),
  textTheme: textTheme.copyWith(
    bodyLarge: textTheme.bodyLarge?.copyWith(color: Colors.white),
    bodyMedium: textTheme.bodyMedium?.copyWith(color: Colors.white),
    bodySmall: textTheme.bodySmall?.copyWith(color: Colors.white),
    headlineLarge: textTheme.headlineLarge?.copyWith(color: Colors.white),
    headlineMedium: textTheme.headlineMedium?.copyWith(color: Colors.white),
    headlineSmall: textTheme.headlineSmall?.copyWith(color: Colors.white),
    titleLarge: textTheme.titleLarge?.copyWith(color: Colors.white),
    titleMedium: textTheme.titleMedium?.copyWith(color: Colors.white),
    titleSmall: textTheme.titleSmall?.copyWith(color: Colors.white),
    labelLarge: textTheme.labelLarge?.copyWith(color: Colors.white),
    labelMedium: textTheme.labelMedium?.copyWith(color: Colors.white),
    labelSmall: textTheme.labelSmall?.copyWith(color: Colors.white),
    displayLarge: textTheme.displayLarge?.copyWith(color: Colors.white),
    displayMedium: textTheme.displayMedium?.copyWith(color: Colors.white),
    displaySmall: textTheme.displaySmall?.copyWith(color: Colors.white),
  ),
  inputDecorationTheme: const InputDecorationTheme(
    filled: true,
    fillColor: surfaceContainerHighDark,
  ),
);